bulletin_board/bulletin_board/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('user/', include('users.urls')),

]

bulletin_board/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

import main.views
from main.views import *

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('advert/<int:pk>/', AdvertDetailView.as_view(), name='advert_detail'),
    path('category/<str:cat_slug>', FilterCatView.as_view(), name='filter_by_categories'),
    path('create_advert/', choose_category, name='choose_category'),
    path('create_advert/<str:slug>', create_advert, name='create_advert'),
    path('see_about', see_about, name='see_about'),
    path('api_advert/', main.views.AdvertView.as_view(), name='api_advert'),
    path('api_category/', main.views.CategoryList.as_view(), name='api_category'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bulletin_board/main/models.py
from django.db import models
from users.models import CustomUser
from mptt.models import MPTTModel, TreeForeignKey


class Category(MPTTModel):
    name = models.CharField(max_length=100, verbose_name='Категория')
    slug = models.SlugField(max_length=100, verbose_name='Url')
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children',
                            verbose_name='Родительская категория')

    class MPTTMeta:
        order_insertion_by = ['name']

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return '%s -> %s' % (self.parent.name, self.name) if self.parent else self.name


class Advert(models.Model):
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE, verbose_name='Автор')
    title = models.CharField(max_length=100, verbose_name='Название')
    category = models.ForeignKey(Category, on_delete=models.PROTECT, verbose_name='Категория')
    content = models.TextField(verbose_name='Описание объявления')
    price = models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')
    publication_datetime = models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')
    edit_datetime = models.DateTimeField(auto_now=True, verbose_name='Дата изменения')
    address = models.CharField(max_length=200, verbose_name='Адрес')
    likes_qty = models.IntegerField(verbose_name='Кол-во лайков', blank=True, null=True)

    class Meta:
        verbose_name = 'Объявление'
        verbose_name_plural = 'Объявления'
        ordering = ['-publication_datetime']

    def __str__(self):
        return self.title


class Gallery(models.Model):
    advert = models.ForeignKey(Advert, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='adverts_images/%Y/%m/%d', verbose_name='Фото к объявлению')

    class Meta:
        verbose_name = 'Галерея'
        verbose_name_plural = 'Галереи'


class CategoryDescription(models.Model):
    category = models.ManyToManyField(Category)
    name = models.CharField(max_length=100, verbose_name='Характеристика категории')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Характеристика категории'
        verbose_name_plural = 'Характеристики категорий'


class DescriptionValue(models.Model):
    advert = models.ForeignKey(Advert, on_delete=models.CASCADE, verbose_name='Объявление')
    description = models.ForeignKey(CategoryDescription, on_delete=models.CASCADE, verbose_name='Характеристика')
    value = models.CharField(max_length=100, verbose_name='Значение характеристики')

    class Meta:
        verbose_name = 'Значение характеристики'
        verbose_name_plural = 'Значения характеристик '

    def __str__(self):
        return f'{self.description.name}: {self.value}'


class Subscribers(models.Model):
    email = models.EmailField(unique=True, verbose_name='E-mail')
    first_name = models.CharField(max_length=100, verbose_name='Имя')

    class Meta:
        verbose_name = 'Подписчик'
        verbose_name_plural = 'Подписчики'

    def __str__(self):
        return self.first_name

bulletin_board/main/forms.py
from django.forms import ModelForm
from main.models import *


class AdvertForm(ModelForm):
    class Meta:
        model = Advert
        fields = ('title', 'content', 'price', 'address')


class SubscribersForm(ModelForm):
    class Meta:
        model = Subscribers
        fields = ('first_name', 'email')

bulletin_board/main/views.py
import os
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.views.generic import DetailView, ListView
from rest_framework.generics import ListCreateAPIView
from main.models import *
from main.forms import *
from django.core.mail import send_mail
from rest_framework.response import Response
from rest_framework.views import APIView
from main.serializers import AdvertSerializer, CategorySerializer
from .tasks import send_email_subscribers


class AdvertView(APIView):
    def get(self, request):
        advert = Advert.objects.all()
        serializer = AdvertSerializer(advert, many=True)
        return Response(serializer.data)


class CategoryList(ListCreateAPIView):
    serializer_class = CategorySerializer
    queryset = Category.objects.all()


class HomeView(ListView):
    model = Advert
    template_name = 'main/index.html'
    context_object_name = 'adverts'


class AdvertDetailView(DetailView):
    model = Advert
    template_name = 'main/advert_detail.html'
    context_object_name = 'adv'


# def filter_by_categories(request, category_pk):
#     category = Category.objects.get(pk=category_pk)
#     adverts = category.advert_set.all()
#     return render(request, 'main/filter_by_categories.html',
#                   {'category': category, 'adverts': adverts, })

class FilterCatView(ListView):
    model = Advert
    template_name = 'main/filter_by_categories.html'
    context_object_name = 'adverts'

    def get_queryset(self):
        cat = Category.objects.get(slug=self.kwargs['cat_slug'])
        return Advert.objects.filter(category__in=cat.get_children()) if cat.get_children() else Advert.objects.filter(
            category__slug=self.kwargs['cat_slug'])


@login_required(login_url='/user/login/')
def choose_category(request):
    categories = Category.objects.all()
    content = {'categories': categories}
    return render(request, 'main/choose_category.html', content)


@login_required(login_url='/user/login/')
def create_advert(request, slug):
    category = Category.objects.get(slug=slug)
    characteristics = category.categorydescription_set.all()
    if request.method == 'POST':
        form = AdvertForm(request.POST)
        gallery = request.FILES.getlist('gallery')
        content = {'category': category, 'form': form, 'characteristics': characteristics}
        if form.is_valid():
            adv = form.save(commit=False)
            adv.author = CustomUser.objects.get(pk=request.user.id)
            adv.category = category
            adv.save()

            for photo in gallery:
                Gallery.objects.create(advert=adv, image=photo)

            for ch in characteristics:
                if request.POST.get(ch.name) != '<не указано>':
                    DescriptionValue.objects.create(advert=adv, description=ch, value=request.POST.get(ch.name))

            return redirect('home')
    else:
        form = AdvertForm()
        content = {'category': category, 'form': form, 'characteristics': characteristics}
    return render(request, 'main/create_advert.html', content)


def see_about(request):
    if request.method == 'POST':
        form = SubscribersForm(request.POST)
        if form.is_valid():
            form.save()
            form = SubscribersForm()
            send_email_subscribers.delay(request.POST.get('email'))
    else:
        form = SubscribersForm()

    return render(request, 'main/see_about.html', {'form': form})

bulletin_board/main/templates/main/advert_detail.html
{% extends 'base.html'%}
{% load mptt_tags %}
{% block title %} {{ advert.title }} {% endblock %}

{% block sidebar %}

{% include 'inc/_sidebar.html' %}

{% endblock %}


{% block advert %}


{% load static %}

<h1>{{ adv.title }}</h1>
<div class="col-md-2 col-md-push-8">
    {{ adv.publication_datetime }}
</div>
<div class="row">

    <div class="col-md-5 col-md-push-4">
        <div id="carousel{{ad.id}}" class="carousel slide" data-bs-ride="carousel" style="width: 500px">
            <div class="carousel-indicators">
                {% for photo in adv.gallery_set.all %}
                {% if forloop.first %}
                <button type="button" data-bs-target="#carousel{{ad.id}}" data-bs-slide-to="{{ forloop.counter0 }}"
                        class="active"
                        aria-current="true" aria-label="Slide {{ forloop.counter }}"></button>
                {% else %}
                <button type="button" data-bs-target="#carousel{{ad.id}}" data-bs-slide-to="{{ forloop.counter0 }}"
                        aria-label="Slide {{ forloop.counter }}"></button>
                {% endif %}
                {% endfor %}
            </div>
            <div class="carousel-inner">
                {% for photo in adv.gallery_set.all %}
                {% if forloop.first %}
                <div class="carousel-item active" data-bs-interval="999999">
                    <img src="{{ photo.image.url }}" class="d-block w-100" alt="..." style="height: 500px">
                </div>
                {% else %}
                <div class="carousel-item" data-bs-interval="999999">
                    <img src="{{ photo.image.url }}" class="d-block w-100" alt="..." style="height: 500px">
                </div>
                {% endif %}
                {% endfor %}
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carousel{{ad.id}}"
                    data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Пред.</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carousel{{ad.id}}"
                    data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">След.</span>
            </button>

        </div>
        <link rel="stylesheet" href="{%static 'css/like.css'%}">
        {% if adv.id in request.session.liked %}

        <form action="{% url 'remove_favorites' adv.id %}" method="POST">
            {% csrf_token %}
            <button class="button dark">
                <div class="hand">
                    <div class="thumb"></div>
                </div>
                <span>Убрать<span>d</span></span>
            </button>

        </form>

        {% else %}

        <form action="{% url 'add_favorites' adv.id %}" method="POST">
            {% csrf_token %}
            <button class="button">
                <div class="hand">
                    <div class="thumb"></div>
                </div>
                <span>Добавить<span>d</span></span>
            </button>
        </form>
        {% endif %}

        <div class="card-body">
            <h5 class="card-title">Категория: {{ adv.category.name }}</h5>
            <p class="card-text">{{ adv.content }}</p>


            <div class="card" style="width: 18rem;">
                {% for val in adv.descriptionvalue_set.all %}
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">{{val}}</li>
                </ul>
                {% endfor %}
            </div>


        </div>


    </div>
    <div class="col-md-2 col-md-pull-4">


        <div class="position-absolute top-1 start-50 ">
            <h3>{{ adv.price }} &#x20bd <br></h3>

            <h6>Контактные данные<br></h6>

            {{ adv.author.first_name}}<br>
            {{ adv.author.phone_number}}<br>
            {{ adv.address }}<br>

        </div>

    </div>
</div>


{% endblock%}

bulletin_board/main/templates/main/choose_category.html
{% extends 'base.html'%}
{% block title %} Добавить объявление {% endblock %}
{% block registration %}

{% load  crispy_forms_tags %}

<div class="list-group" style="width: 250px">
    {%for cat in categories%}
        <a href="{% url 'create_advert' cat.slug %}" class="list-group-item list-group-item-action">{{cat.name}}</a>
    {%endfor%}
</div>


{% endblock %}

bulletin_board/main/templates/main/create_advert.html
{% extends 'base.html'%}
{% block title %} Добавить объявление {% endblock %}
{% block registration %}

{% load  crispy_forms_tags %}

<div class="col-md-4">
    <p>{{category}}</p>
    <form action="#" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form|crispy }}

        {% for ch in characteristics %}
        <p>{{ch}}<br><input type="text" name="{{ch}}" value="<не указано>"></p>
        {% endfor %}

        <p><input type="file" name="gallery" multiple></p>

        <button type="submit" class="btn btn-primary">Создать</button>
    </form>
</div>

{% endblock %}

bulletin_board/main/templates/main/filter_by_categories.html
{% extends 'base.html'%}
{% block title %}{{category.name}} {% endblock %}

{% load static %}

{% block sidebar %}

{% include 'inc/_sidebar.html' %}

{% endblock %}


{% block advert %}

<div class="col-md-8">
    <div class="container">
        {% if not adverts %}
        <link rel="stylesheet" href="{%static 'css/text.css'%}">
        <div class="wrapper">
            <div class="typing-demo">
                В данной категории нет объявлений
            </div>
        </div>
        {% endif %}
    </div>
</div>

{% include 'inc/_advert.html' %}

{% endblock%}

bulletin_board/main/templates/main/index.html
{% extends 'base.html'%}
{% block title %} Обьявления {% endblock %}

{% load mptt_tags %}
{% load static %}

{% block sidebar %}

{% include 'inc/_sidebar.html' %}

{% endblock %}


{% block advert %}

{% include 'inc/_advert.html' %}

{% endblock%}

bulletin_board/main/templates/main/see_about.html
{% extends 'base.html'%}
{% block title %} О нас {% endblock %}
{% load  crispy_forms_tags %}
{% load static %}

{% block about %}

<div class="col-md-8">
    <div class="card mb-2" style="max-width: 1540px;">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="{% static 'img/about/bul_bor.jpg' %}" width="200" alt="...">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">Информация</h5>
                    <p class="card-text"><b>Разработчики:</b><br>
                        Евгений Лебедев - lebedewhs@yandex.ru<br>
                        Дмитрий Виляховец - dmitriy.vilyakhovets@gmail.com
                    </p>
                    <p class="card-text"><b>Используемые технологии:</b><br>
                        - Django + DRF<br>
                        - Celery + Redis<br>
                        - Docker<br>
                        - PostgreSQL
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

{% block subscription %}
<h1>Подписка на новости сайта</h1>
<div class="col-md-4">

    <form action="#" method="post">
        {% csrf_token %}
        {{form|crispy }}<br>
        <button type="submit" class="btn btn-primary">Подписаться</button>
    </form>
</div>
{% endblock %}